src/config.c

Swappy segfaults if it is invoked with unknown command-line flags

fix(init): fix segfault for unknown flags

---

src/application.c
src/pixbuf.c

Swappy tried to access Gtk data after the end of the mainloop and the
file save routine had infinite recursion

fix(application): fix file loop and use of GTK object after lifecycle

---

src/application.c

The bug was introduced by `f3e5d86`.
Closes #8

fix(application): properly save output file upon clean exit

---

src/clipboard.c
src/pixbuf.c

This fixes the scaling issue when user would copy or save the file.
Commit `445980b` only solved the rendering part not the pixbuf part.
Closes #6

fix(pixbuf): properly grab pixbuf size from cairo surface

---

README.md

Remove unnecessary tabs in README.md

docs(readme): better styling in config section

---

.versionrc
README.md
script/bump-meson-build.js

Mixing C code with Javascript files, what's not to love.
Simply run the following line to generate a new standard version:
```
npx standard-version --sign
```

chore(release): add bump meson script

---

meson.build
res/icons/hicolor/scalable/apps/swappy.svg
res/meson.build
res/swappy.glade
src/po/LINGUAS
src/po/POTFILES
src/po/en.po
src/po/meson.build
src/po/swappy.desktop.in
src/po/swappy.pot

- use of `gettext` with `meson` i18n module.
- Includes the first swappy logo, yay !
- Includes a desktop file that registers mime type for png files

feat(i18n): add translatable desktop file

---

README.md

swappy will be in the official repos for openSUSE Tumbleweed.

docs(readme): Add openSUSE install

---

include/swappy.h
include/util.h
src/paint.c
src/render.c
src/util.c

UTF-8 characters are now handled porperly. Also re-worked some helper
functions with UTF-8 in mind.
Closes #43

fix(text): properly handle utf-8 chars

---

src/application.c

Most of the `i18n` boilerplate was there, but the app still needed to
know what domain to look for. This must happen after initialization of
the `GtkBuilder` and before loading the glade file.
The domain is simply the `mo` file packaged with the app and usually
located under:
```
/usr/share/locale/$LANG/LC_MESSAGES/$APP.mo
```
Once again thanks to @maximbaz for pointing it out.
Closes #92

fix(i18n): properly set translation domain during layout init

---

src/pixbuf.c

Most of the filesystems have max filename limited to 255 chars.
Let's set that limit and handle the case where the resulting `strftime`
format is larger.
Closes #74

fix(pixbuf): handle overflow when filename_format is too long

---

include/pixbuf.h
src/application.c
src/pixbuf.c

If the input file is invalid (example: `grim` did not work due to
invalid geometry), handle the error gracefully.
Previously we had a coredump due to `g_error`.

fix(pixbuf): handle invalid input file

---

src/po/swappy.desktop.in

I'm working on packaging this for Gentoo, and the Annotation category is not a valid category in the xdg specification, causing problems for our build process.
See https://specifications.freedesktop.org/menu-spec/latest/apa.html
See https://github.com/gentoo/gentoo/pull/18652#pullrequestreview-601579680

Remove Annotation keyword from desktop categories

---

README.md
include/config.h
include/swappy.h
src/application.c
src/config.c
swappy.1.scd

I have made 2 changes:
1. The current behavior of swappy is to assume `save_dir` to exist, when trying to save edited image to a non-existing `save_dir`, swappy does not save it at all.  In 0b1c6e9, I add code to attempt to create `save_dir` if it does not already exists.
2. I also added a configuration option `paint_mode` in b6c2c60, to allow a user to configure the start up painting mode of swappy.
Documentation and readme are updated according to the above 2 modifications in 476ae90.

Create `save_dir` if it does not exist, and allow configuration of starting painting mode

---

README.md
include/config.h
include/swappy.h
src/application.c
src/clipboard.c
src/config.c
swappy.1.scd

if the quit_on_copy config option is set to true, the application now exits after copying the selection to the keyboard

feat(config): add quit_on_copy config

---

README.md
include/config.h
include/swappy.h
res/swappy.glade
src/application.c
src/config.c
src/paint.c
src/render.c
swappy.1.scd

Closes #120
This adds an option on top of existing brush types, to allow for filled shapes in addition to non-filled ones.
I tried to follow the surrounding style as much as possible, but let me know if something isn't quite right :sweat_smile:

Allow filling rectangles and ellipsis 

---

res/swappy.glade

The non-symbolic variant might be indistinguishable from the background.
Fixes #34
Ref: https://wiki.gnome.org/Design/OS/SymbolicIcons
`GTK_THEME=Materia swappy -f foo.png:`
`GTK_THEME=Materia-light swappy -f foo.png:`
`GTK_THEME=Materia-dark swappy -f foo.png:`
`GTK_THEME=Materia swappy -f foo.png:`
`GTK_THEME=Materia-light swappy -f foo.png:`
`GTK_THEME=Materia-dark swappy -f foo.png:`

fix(ui): Use *-symbolic variant of toolbar icons

---

CHANGELOG.md
README.md
script/github-release

Found via `typos --hidden --format brief`

chore: fix typos

---

res/style/swappy.css

The current css specifies "FontAwesome 5 Free Solid", for .drawing and .text-button. This results in the button icons/fonts not rendering correctly on systems that do not have that exact version of FontAwesome. This change allows the icons/fonts to be rendered correctly on these systems.
This should resolve issues like https://github.com/jtheoof/swappy/issues/91 without users having to modify their local gtk css configurations.
BTW, I'm really liking swappy: IMO it has just the right balance of ease of use vs features. Thanks for the great software.

fix(ui): Specify a non-versioned FontAwesome

---

README.md
include/config.h
include/swappy.h
src/application.c
src/config.c
swappy.1.scd

This PR adds a config option to set the default color for the custom color option.
This way, if you often use the same color, you can set it as a config option.
It uses the gdk function `gdk_rgba_parse` which supports `hex, rgb(),rgba()` aswell as a standard name.
Docs:
> The string can be either one of: - A standard name (Taken from the X11 rgb.txt file). - A hexadecimal value in the form “#rgb”, “#rrggbb”, “#rrrgggbbb” or ”#rrrrggggbbbb” - A RGB color in the form “rgb(r,g,b)” (In this case the color will have full opacity) - A RGBA color in the form “rgba(r,g,b,a)”
As for the changes in `application.c`. I was not sure where I should put the code to initialize this color.
If you can tell me where it should go I will change it.

Add a custom_color config option

---

swappy.1.scd

docs: Add custom_color accepted formats to doc

---

src/config.c

When trying to rebase my changes on top of the latest master branch, I found out two problems that slipped through the review of  PR#185. Fortunately the fixes are rather straightforward.

Custom color fixes

---

README.md
src/application.c
swappy.1.scd

`e` :Switch to Text, (short for edit)
`c`: Switch to Ellipse  (short for circle)
x:  Clear Paints  
It is more advantageous to use the left hand to change shapes, while controlling the mouse with the right hand.

add some keybinding to use left hand
